// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IERC165$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IERC165";
  readonly sourceName: "contracts/DiamondInterfaces/IERC165.sol";
  readonly abi: [{"inputs":[{"internalType":"bytes4","name":"interfaceId","type":"bytes4"}],"name":"supportsInterface","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/DiamondInterfaces/IERC165.sol";
  readonly buildInfoId: "solc-0_8_24-ac5164326b1b41285633d2ef1c11c790d25e3646";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IERC165"]: IERC165$Type;
    ["contracts/DiamondInterfaces/IERC165.sol:IERC165"]: IERC165$Type;
  }
}