// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface OwnershipFacet$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "OwnershipFacet";
  readonly sourceName: "contracts/OwnershipFacet.sol";
  readonly abi: [{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"previousOwner","type":"address"},{"indexed":true,"internalType":"address","name":"newOwner","type":"address"}],"name":"OwnershipTransferred","type":"event"},{"inputs":[],"name":"owner","outputs":[{"internalType":"address","name":"owner_","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"_newOwner","type":"address"}],"name":"transferOwnership","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x6080806040523461001657610170908161001c8239f35b600080fdfe608080604052600436101561001357600080fd5b600090813560e01c9081638da5cb5b146100f2575063f2fde38b1461003757600080fd5b346100ef5760203660031901126100ef576001600160a01b03600435818116908190036100eb577fc8fcad8db84d3cc18b4c41d551ea0ee66dd599cde068d998e57d5e09332c131d918254908116330361009b576001600160a01b03191617905580f35b60405162461bcd60e51b815260206004820152602260248201527f4c69624469616d6f6e643a204d75737420626520636f6e7472616374206f776e60448201526132b960f11b6064820152608490fd5b8280fd5b80fd5b9050346101365781600319360112610136577fc8fcad8db84d3cc18b4c41d551ea0ee66dd599cde068d998e57d5e09332c131e546001600160a01b03168152602090f35b5080fdfea26469706673582212208f2bc9fd1f043f894310e93ab19a9898e815901904db126e7a1a08137960f6ca64736f6c63430008180033";
  readonly deployedBytecode: "0x608080604052600436101561001357600080fd5b600090813560e01c9081638da5cb5b146100f2575063f2fde38b1461003757600080fd5b346100ef5760203660031901126100ef576001600160a01b03600435818116908190036100eb577fc8fcad8db84d3cc18b4c41d551ea0ee66dd599cde068d998e57d5e09332c131d918254908116330361009b576001600160a01b03191617905580f35b60405162461bcd60e51b815260206004820152602260248201527f4c69624469616d6f6e643a204d75737420626520636f6e7472616374206f776e60448201526132b960f11b6064820152608490fd5b8280fd5b80fd5b9050346101365781600319360112610136577fc8fcad8db84d3cc18b4c41d551ea0ee66dd599cde068d998e57d5e09332c131e546001600160a01b03168152602090f35b5080fdfea26469706673582212208f2bc9fd1f043f894310e93ab19a9898e815901904db126e7a1a08137960f6ca64736f6c63430008180033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/OwnershipFacet.sol";
  readonly buildInfoId: "solc-0_8_24-ac5164326b1b41285633d2ef1c11c790d25e3646";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["OwnershipFacet"]: OwnershipFacet$Type;
    ["contracts/OwnershipFacet.sol:OwnershipFacet"]: OwnershipFacet$Type;
  }
}