// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface DiamondInit$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "DiamondInit";
  readonly sourceName: "contracts/upgradeInitializers/DiamondInit.sol";
  readonly abi: [{"inputs":[],"name":"init","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x608080604052346100155760ec908161001b8239f35b600080fdfe6004361015600c57600080fd5b6000803560e01c63e1c7392a14602157600080fd5b3460b3578060031936011260b3576301ffc9a760e01b81527fc8fcad8db84d3cc18b4c41d551ea0ee66dd599cde068d998e57d5e09332c132760205260408082208054600160ff1991821681179092556307e4c70760e21b845282842080548216831790556348e2b09360e01b845282842080548216831790556307f5828d60e41b8452918320805490921617905580f35b80fdfea26469706673582212203eb2dda81708659bb2ce2f9097fb05a23935073119c2ba4046a1e5a2ddba531464736f6c63430008180033";
  readonly deployedBytecode: "0x6004361015600c57600080fd5b6000803560e01c63e1c7392a14602157600080fd5b3460b3578060031936011260b3576301ffc9a760e01b81527fc8fcad8db84d3cc18b4c41d551ea0ee66dd599cde068d998e57d5e09332c132760205260408082208054600160ff1991821681179092556307e4c70760e21b845282842080548216831790556348e2b09360e01b845282842080548216831790556307f5828d60e41b8452918320805490921617905580f35b80fdfea26469706673582212203eb2dda81708659bb2ce2f9097fb05a23935073119c2ba4046a1e5a2ddba531464736f6c63430008180033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/upgradeInitializers/DiamondInit.sol";
  readonly buildInfoId: "solc-0_8_24-ac5164326b1b41285633d2ef1c11c790d25e3646";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["DiamondInit"]: DiamondInit$Type;
    ["contracts/upgradeInitializers/DiamondInit.sol:DiamondInit"]: DiamondInit$Type;
  }
}