// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface EcosystemLib$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "EcosystemLib";
  readonly sourceName: "contracts/DiamondLibrary/EcosystemLib.sol";
  readonly abi: [];
  readonly bytecode: "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea26469706673582212209bd39fe7211328334e28e3214ec47be5913ca02126e127fb52294f10c6e403fc64736f6c63430008180033";
  readonly deployedBytecode: "0x600080fdfea26469706673582212209bd39fe7211328334e28e3214ec47be5913ca02126e127fb52294f10c6e403fc64736f6c63430008180033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/DiamondLibrary/EcosystemLib.sol";
  readonly buildInfoId: "solc-0_8_24-ac5164326b1b41285633d2ef1c11c790d25e3646";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["EcosystemLib"]: EcosystemLib$Type;
    ["contracts/DiamondLibrary/EcosystemLib.sol:EcosystemLib"]: EcosystemLib$Type;
  }
}